- name: Add Postgresql GPG key.
  rpm_key:
    key: "{{ pg_gpg_key }}"
    state: present
  become: yes
  when: pg_gpg_install_key

- name: create Postsgresql repo
  template: src=postgresql_repo.j2 dest=/etc/yum.repos.d/postgresql.repo
            owner=root group=root mode=0644
  become: yes

- name: Install postgresql
  yum: pkg="{{ package }}" state=installed
  with_items: "{{ pg_packages }}"
  loop_control:
    loop_var: package
  become: yes

- name: Check data dir
  command: ls /var/lib/pgsql/{{ pg_version }}/data
  register: data_dir_check
  become: yes

- name: Initialize database
  command: service postgresql-{{ pg_version }} initdb
  register: init_db_output
  when: data_dir_check.stdout == ""
  become: yes

- name: run handler now
  meta: flush_handlers
  when: init_db_output.changed

